### ISSUE TITLE
Enum abstract methods

### ISSUE THREAD

**Issue by ben-manes** [square/javapoet#193]
I didn't see this in the test cases so please correct me if I'm wrong. I'm experimenting at the moment.

I'd like to generate an enum with an abstract method which each enumeration implements. If I mark the enum `TypeSpec`'s method as `abstract` I receive the erro:r
```java
Exception in thread "main" java.lang.IllegalArgumentException: non-abstract type NodeFactory cannot declare abstract method newNode
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.squareup.javapoet.TypeSpec$Builder.build(TypeSpec.java:380)
```

If I remove this modifier an empty method is generated. The solution for now is to allow each enumeration to override that method versus implement it.

Below is the snippet I'm playing with. This is for code generating the 96 optimized variants of cache entry nodes in a Java 8 [rewrite](https://github.com/ben-manes/caffeine) of Guava's Cache.

```java
public final class NodeGenerator {

  public void generate() throws IOException {
    TypeSpec nodeFactory = TypeSpec.enumBuilder("NodeFactory")
        .addJavadoc("<em>WARNING: GENERATED CODE</em>\n\n")
        .addJavadoc("A factory for cache nodes optimized for a particular configuration.\n")
        .addJavadoc("\n@author ben.manes@gmail.com (Ben Manes)\n")
        .addEnumConstant("STRONG", nodeSpec())
        .addMethod(newNode() /* .addModifiers(Modifier.ABSTRACT) */.build())
        .build();
    JavaFile javaFile = JavaFile.builder(getClass().getPackage().getName(), nodeFactory)
        .addFileComment("Copyright 2015 Ben Manes. All Rights Reserved.")
        .build();
    javaFile.emit(System.out);
  }

  public TypeSpec nodeSpec() {
    MethodSpec newNodeSpec = MethodSpec.methodBuilder("newNode").build();
    return TypeSpec.anonymousClassBuilder("")
        .addMethod(newNodeSpec)
        .build();
  }

  private MethodSpec.Builder newNode() {
    return MethodSpec.methodBuilder("newNode");
  }

  public static void main(String[] args) throws IOException {
    new NodeGenerator().generate();
  }
}
```

**Comment by JakeWharton** [comment]
Yep. It's a bug!

We can sit the test case next to [`enumWithSubclassing`][1].

 [1]: https://github.com/square/javapoet/blob/001514081886abd2a78407f2882cc4f7a959260b/src/test/java/com/squareup/javapoet/TypeSpecTest.java#L287-L337
