### ISSUE TITLE
Eager `$N` validation

### ISSUE THREAD

**Issue by swankjesse** [square/javapoet#219]
Right now some emit validation doesn't happen until the file is written. This makes for hard-to-debug problems because the source of the problem isn't reflected in the stacktrace.

```
java.lang.IllegalArgumentException: expected name but was com.squareup.franklin.email.butter.DbButterCampaignCriteriaBuilder
	at com.squareup.javapoet.CodeWriter.toName(CodeWriter.java:406)
	at com.squareup.javapoet.CodeWriter.emitName(CodeWriter.java:397)
	at com.squareup.javapoet.CodeWriter.emit(CodeWriter.java:207)
	at com.squareup.javapoet.MethodSpec.emit(MethodSpec.java:118)
	at com.squareup.javapoet.TypeSpec.emit(TypeSpec.java:213)
	at com.squareup.javapoet.JavaFile.emit(JavaFile.java:139)
	at com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:66)
	at com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:106)
```

**Comment by ben-manes** [comment]
Just hit this exact issue and came to report it =)
