### ISSUE TITLE
StackOverflowError: TypeName.get() for "Foo<T extends Foo<T>>"

### ISSUE THREAD

**Issue by weijunkong** [square/javapoet#237]
While experimenting with JavaPoet I found that  a ```StackOverflowError``` occurs when calling ``TypeName.get(typeMirror)`` for a TypeMirror that represents the following class declaration which has a recursive type variable. 

```java
public class Foo<T extends Foo<T>> {}
```

And here is the stacktrace:-
```
Caused by: java.lang.StackOverflowError
        at javax.lang.model.util.AbstractTypeVisitor6.<init>(AbstractTypeVisitor6.java:69)
        at javax.lang.model.util.SimpleTypeVisitor6.<init>(SimpleTypeVisitor6.java:103)
        at javax.lang.model.util.SimpleTypeVisitor7.<init>(SimpleTypeVisitor7.java:80)
        at com.squareup.javapoet.TypeName$1.<init>(TypeName.java:155)
        at com.squareup.javapoet.TypeName.get(TypeName.java:155)
        at com.squareup.javapoet.TypeVariableName.get(TypeVariableName.java:88)
        at com.squareup.javapoet.TypeName$1.visitTypeVariable(TypeName.java:195)
        at com.squareup.javapoet.TypeName$1.visitTypeVariable(TypeName.java:155)
        at com.sun.tools.javac.code.Type$TypeVar.accept(Type.java:1495)
        at com.squareup.javapoet.TypeName.get(TypeName.java:155)
```

Class Foo in isn't something I can change in this case, so it would be great if JavaPoet could handle this. Please also let me know if there are any workarounds in the mean time.

**Comment by swankjesse** [comment]
I ran into something like this myself when trying to declare a type with this structure. Will fix.

**Comment by freetigerliu** [comment]
Is anyone working on this? If not I could fix it with a naive solution handling T extends Foo<T> as T +  special-stable-token. It might not solve all the recursive cases, but it will cover most of them. This is a blocking issue.

**Comment by swankjesse** [comment]
Not actively working on it unfortunately. The right fix is pretty difficult here; we need to detect the recursion.

**Comment by freetigerliu** [comment]
Not sure I understand you. If a Type T extends a ParameterizedType whose typeArguments includes T, then there is a recusion. Why that is hard?

**Comment by swankjesse** [comment]
The reference to T may be many levels deep, like `T extends List<List<List<T>>`.

**Comment by freetigerliu** [comment]
do you think this will work?
boolean hasT(Type someType, Type t) {
   if (someType.equals(t)) {
    return true;
  }
  if (!someType instanceof ParameterizedType) {
    return false;
  } 
  for (Type child : ((ParameterizedType) someType).getActualTypeArguments()) {
    if (hasT(child)) {
     return true;
    }
  }
  return false;
}

**Comment by swankjesse** [comment]
Thanks @eamonnmcmanus !
