### ISSUE TITLE
it's hard to see the error.

### ISSUE THREAD

**Issue by jiqimaogou** [square/javapoet#269]
```
d by: java.lang.IllegalArgumentException: expected name but was name
   at com.squareup.javapoet.CodeWriter.toName(CodeWriter.java:406)
   at com.squareup.javapoet.CodeWriter.emitName(CodeWriter.java:397)
   at com.squareup.javapoet.CodeWriter.emit(CodeWriter.java:207)
   at com.squareup.javapoet.MethodSpec.emit(MethodSpec.java:118)
   at com.squareup.javapoet.TypeSpec.emit(TypeSpec.java:213)
   at com.squareup.javapoet.JavaFile.emit(JavaFile.java:139)
   at com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:66)
   at com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:106)
```

I just see the IllegalArgumentException, but I don't know which is illegal.

**Comment by swankjesse** [comment]
Yup, agreed. I think we want to instead catch this when you add the value to a code block. Want to contribute a fix?

**Comment by jiqimaogou** [comment]
ok, I'll try it.
