### ISSUE TITLE
Indexed and positional CodeBlock replacement blocks error

### ISSUE THREAD

**Issue by JakeWharton** [square/javapoet#309]
..is awful. I don't have an example right now, but both too few and too many arguments create misleading exceptions based on list iteration.

**Comment by JakeWharton** [comment]
```
Exception in thread "main" java.util.NoSuchElementException
	at java.util.AbstractList$Itr.next(AbstractList.java:364)
	at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:147)
	at com.squareup.wire.java.TypeWriter.messageToString(TypeWriter.java:563)
	at com.squareup.wire.java.TypeWriter.toTypeSpec(TypeWriter.java:341)
	at com.squareup.wire.java.TypeWriter.toTypeSpec(TypeWriter.java:86)
	at com.squareup.wire.WireCompiler.compile(WireCompiler.java:95)
	at com.squareup.wire.WireCompiler.main(WireCompiler.java:46)
```
