### ISSUE TITLE
StackOverflowError with generic types

### ISSUE THREAD

**Issue by sormuras** [square/javapoet#356]
There's a circle in `TypeName.get/list`, `ParameterizedTypeName.get` and `TypeVariableName.get`. The following test:
```java
  private <E extends Enum<E>> E recursiveEnum(E[] values) {
    return values[0];
  }
  
  @Test public void genericTypes() throws Exception {
    Method recursiveEnum = getClass().getDeclaredMethod("recursiveEnum", Enum[].class);
    TypeName.get(recursiveEnum.getReturnType());
    TypeName.get(recursiveEnum.getGenericReturnType()); // StackOverflowError !!!
    TypeName.get(recursiveEnum.getParameterTypes()[0]);
    TypeName.get(recursiveEnum.getGenericParameterTypes()[0]); // StackOverflowError !!!
  }
```
produces a endless stack trace like:
```
Caused by: java.lang.StackOverflowError
	at java.lang.Class.getSimpleBinaryName(Class.java:1443)
	at java.lang.Class.getSimpleName(Class.java:1309)
	at com.squareup.javapoet.ClassName.get(ClassName.java:113)
	at com.squareup.javapoet.ParameterizedTypeName.get(ParameterizedTypeName.java:76)
	at com.squareup.javapoet.TypeName.get(TypeName.java:260)
	at com.squareup.javapoet.TypeName.list(TypeName.java:280)
	at com.squareup.javapoet.TypeVariableName.get(TypeVariableName.java:129)
	at com.squareup.javapoet.TypeName.get(TypeName.java:266)
	at com.squareup.javapoet.TypeName.list(TypeName.java:280)
	at com.squareup.javapoet.ParameterizedTypeName.get(ParameterizedTypeName.java:77)
	at com.squareup.javapoet.TypeName.get(TypeName.java:260)
	at com.squareup.javapoet.TypeName.list(TypeName.java:280)
	at com.squareup.javapoet.TypeVariableName.get(TypeVariableName.java:129)
	at com.squareup.javapoet.TypeName.get(TypeName.java:266)
	at com.squareup.javapoet.TypeName.list(TypeName.java:280)
	at com.squareup.javapoet.ParameterizedTypeName.get(ParameterizedTypeName.java:77)
	at com.squareup.javapoet.TypeName.get(TypeName.java:260)
```

**Comment by sormuras** [comment]
Related to https://github.com/square/javapoet/commit/6551850b3eaa4f5ff4b6ce6a2b2102d281a11fee ?
