### ISSUE TITLE
NoClassDefFoundError com/squareup/javapoet/MethodSpec

### ISSUE THREAD

**Issue by VernonLee** [square/javapoet#635]
你好，在 android studio 中创建一个 Java Library, 创建类并且添加 main 方法，编译正常，但是运行的时候报如下错误：

Exception in thread "main" java.lang.NoClassDefFoundError: com/squareup/javapoet/MethodSpec
	at com.nodlee.code.CodeGenerateManager.generate(CodeGenerateManager.java:19)
	at com.nodlee.code.CodeGenerateManager.main(CodeGenerateManager.java:15)
Caused by: java.lang.ClassNotFoundException: com.squareup.javapoet.MethodSpec
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

**Comment by JakeWharton** [comment]
This appears to by a build system problem and not one of JavaPoet itself. The JavaPoet jar isn't being added to your classpath.
