### ISSUE TITLE
Deadlock in Java 8

### ISSUE THREAD

**Issue by justinuang** [square/javapoet#637]
We are seeing deadlocks when running several different instances of java poet in parallel threads

```
"Task worker for ':' Thread 2" #147 prio=5 os_prio=0 tid=0x00007fcdb870a000 nid=0x6894 in Object.wait() [0x00007fcd0b8f8000]
   java.lang.Thread.State: RUNNABLE
        at com.squareup.javapoet.TypeSpec$Builder.<init>(TypeSpec.java:403)
        at com.squareup.javapoet.TypeSpec$Builder.<init>(TypeSpec.java:394)
        at com.squareup.javapoet.TypeSpec.interfaceBuilder(TypeSpec.java:121)
        ...

"Task worker for ':' Thread 3" #148 prio=5 os_prio=0 tid=0x00007fcdb870b000 nid=0x6895 in Object.wait() [0x00007fcd0b7f7000]
   java.lang.Thread.State: RUNNABLE
        at com.squareup.javapoet.TypeSpec$Builder.<init>(TypeSpec.java:403)
        at com.squareup.javapoet.TypeSpec$Builder.<init>(TypeSpec.java:394)
        at com.squareup.javapoet.TypeSpec.interfaceBuilder(TypeSpec.java:121)
        ...
```

The current hypothesis is that it is related to https://bugs.openjdk.java.net/browse/JDK-8037567, where [ClassName](https://github.com/square/javapoet/blob/d91f8e1374f7ccdb68d92c206c84864cd09c02f6/src/main/java/com/squareup/javapoet/ClassName.java) is a subclass of TypeName, but TypeName has a static variable of type ClassName [here](https://github.com/square/javapoet/blob/d91f8e1374f7ccdb68d92c206c84864cd09c02f6/src/main/java/com/squareup/javapoet/TypeName.java#L78).

**Comment by justinuang** [comment]
Ping on this.

**Comment by swankjesse** [comment]
Wanna send a pull request with a fix? I'm unsure of what the best solution is.

**Comment by kenzierocks** [comment]
This should really be fixed, as it means Javapoet can't easily be used in a multi-threaded environment.

The issue is that `TypeName` has static constants that load its subclasses (`ClassName`). If you initialize `ClassName` in one thread while simultaneously initializing `TypeName` in another, the `ClassName` thread will try to acquire the `TypeName` class loading lock, and the `TypeName` thread will try to acquire the `ClassName` class loading lock, thus creating a deadlock.

The solution here is not an easy one.It requires breaking existing API (not great) and making all `ClassName` constants into lazily-loaded fields locked behind public methods, so that `TypeName`'s initialization does not require loading `ClassName`. Only `OBJECT` fits this candidate, so it may not be that harsh of a change. It can also become a static field on `ClassName` or a new `TypeNames` class, if that's what you want the API to look like, but it can't stay as is.

My current workaround is loading `TypeName` before any other code in my application runs, but that's obviously pretty strange to need to do that.

**Comment by carterkozak** [comment]
I ran into this issue today, unfortunately in one codepath it's nearly 100% reproducible! I've provided a potential fix with the drawback that @octylFractal pointed out.

What do you think?
