### ISSUE TITLE
If a code statement contains '$' character, then an exception is thrown

### ISSUE THREAD

**Issue by acabarbaye** [square/javapoet#670]
if the statement string contains a '$' like "return (endpointName == null || endpointName.matches(\"^[ -~]{16,64}$\"))" for instance, then the following exception is thrown:
```
Exception in thread "main" java.lang.IllegalArgumentException: index 1 for '$"' not in range (received 0 arguments)
	at com.squareup.javapoet.Util.checkArgument(Util.java:53)
	at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:287)
	at com.squareup.javapoet.CodeBlock$Builder.addStatement(CodeBlock.java:402)
	at com.squareup.javapoet.MethodSpec$Builder.addStatement(MethodSpec.java:480)
```

**Comment by kenzierocks** [comment]
You should use `$$` if you want a literal dollar sign. JavaPoet offers certain placeholders using `$` (see [this](https://github.com/square/javapoet#user-content-l-for-literals)) so you must encode your dollar signs.

**Comment by acabarbaye** [comment]
Thanks for your answer.
I read the documentation regarding `$` use. However, `$$` was never mentioned.
