### ISSUE TITLE
Add context information to exception messages

### ISSUE THREAD

**Issue by vlsi** [square/javapoet#763]
For instance:

```
    java.lang.IllegalArgumentException: invalid format string: 'com.squareup.javapoet.TypeSpec$Builder@b25f88e'
        at com.squareup.javapoet.CodeBlock$Builder.addArgument(CodeBlock.java:334)
        at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:292)
        at com.squareup.javapoet.CodeBlock.of(CodeBlock.java:105)
```

or

```
    java.lang.IllegalStateException: statement enter $[ followed by statement enter $[
        at com.squareup.javapoet.Util.checkState(Util.java:62)
        at com.squareup.javapoet.CodeWriter.emit(CodeWriter.java:282)
        at com.squareup.javapoet.MethodSpec.emit(MethodSpec.java:139)
        at com.squareup.javapoet.TypeSpec.emit(TypeSpec.java:322)
        at com.squareup.javapoet.JavaFile.emit(JavaFile.java:217)
        at com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:95)
        at com.squareup.javapoet.JavaFile.toString(JavaFile.java:236)
        at com.squareup.javapoet.JavaFile$2.getCharContent(JavaFile.java:251)
        at com.squareup.javapoet.JavaFile$2.getCharContent(JavaFile.java:248)
        at org.javacc.fuzzer.FuzzParserGenerator.generate(FuzzParserGenerator.kt:25)
        at org.javacc.parser.Main.mainProgram(Main.java:259)
        at org.javacc.fuzzer.test.FuzzGenerationTest.generateParser(FuzzGenerationTest.kt:37)
        at org.javacc.fuzzer.test.FuzzGenerationTest.generateParser$default(FuzzGenerationTest.kt:23)
        at org.javacc.fuzzer.test.FuzzGenerationTest.simpleFuzzer$javacc(FuzzGenerationTest.kt:13)
```

I see there's `statement enter $[ followed by statement enter $[`, however, the context is not really clear.

It would be great if JavaPoet could re-construct partially invalid code, and highlight what went wrong.

It would be nice to have a debug mode, where JavaPoet would record the stacktrace for each `Builder` generation (or `addCode`-like call), so it could report the stacktrace (or something like that) where the bad `CodeBlock` was created.

**Comment by vlsi** [comment]
Regarding the second exception. It happens when the code is emitted to `NULL_APPENDABLE`.

One of the options is to catch the exception and rerun it with a true appendable, so the exception message could include the bits of the generated code and position of the failure.

**Comment by qwer87511** [comment]
> For instance:
> 
> ```
>     java.lang.IllegalArgumentException: invalid format string: 'com.squareup.javapoet.TypeSpec$Builder@b25f88e'
>         at com.squareup.javapoet.CodeBlock$Builder.addArgument(CodeBlock.java:334)
>         at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:292)
>         at com.squareup.javapoet.CodeBlock.of(CodeBlock.java:105)
> ```
> 
> or
> 
> ```
>     java.lang.IllegalStateException: statement enter $[ followed by statement enter $[
>         at com.squareup.javapoet.Util.checkState(Util.java:62)
>         at com.squareup.javapoet.CodeWriter.emit(CodeWriter.java:282)
>         at com.squareup.javapoet.MethodSpec.emit(MethodSpec.java:139)
>         at com.squareup.javapoet.TypeSpec.emit(TypeSpec.java:322)
>         at com.squareup.javapoet.JavaFile.emit(JavaFile.java:217)
>         at com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:95)
>         at com.squareup.javapoet.JavaFile.toString(JavaFile.java:236)
>         at com.squareup.javapoet.JavaFile$2.getCharContent(JavaFile.java:251)
>         at com.squareup.javapoet.JavaFile$2.getCharContent(JavaFile.java:248)
>         at org.javacc.fuzzer.FuzzParserGenerator.generate(FuzzParserGenerator.kt:25)
>         at org.javacc.parser.Main.mainProgram(Main.java:259)
>         at org.javacc.fuzzer.test.FuzzGenerationTest.generateParser(FuzzGenerationTest.kt:37)
>         at org.javacc.fuzzer.test.FuzzGenerationTest.generateParser$default(FuzzGenerationTest.kt:23)
>         at org.javacc.fuzzer.test.FuzzGenerationTest.simpleFuzzer$javacc(FuzzGenerationTest.kt:13)
> ```
> 
> I see there's `statement enter $[ followed by statement enter $[`, however, the context is not really clear.
> 
> Just in case, `FuzzParserGenerator.generate(FuzzParserGenerator.kt:25` is
> 
> ```kotlin
> println(file.getCharContent(true)) // file is JavaFileObject produced by JavaPoet
> ```
> 
> It would be great if JavaPoet could re-construct partially invalid code, and highlight what went wrong (see https://elm-lang.org/news/compiler-errors-for-humans )
> 
> It would be nice to have a debug mode, where JavaPoet would record the stacktrace for each `Builder` generation (or `addCode`-like call), so it could report the stacktrace (or something like that) where the bad `CodeBlock` was created.

在我的案例中，我使用 methodBuilder.addStatement()
`Method.Builder methodBuilder` and `CodeBlock code`
i fix my bug by replacing `methodBuilder.addStatement(code)`
with `methodBuilder.add(code)`

**Comment by liujianpc** [comment]
您好，本人已收到您的邮件！谢谢！      祝您工作顺利，生活愉快！

**Comment by gdgaoxiaoming** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thank you .
        have a nice day .
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        8/16/2022 17:28
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [square/javapoet] Add context information to exception messages (#763)
        
      
    
  
  



For instance:

    java.lang.IllegalArgumentException: invalid format string: ***@***.***'

        at com.squareup.javapoet.CodeBlock$Builder.addArgument(CodeBlock.java:334)

        at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:292)

        at com.squareup.javapoet.CodeBlock.of(CodeBlock.java:105)



or

    java.lang.IllegalStateException: statement enter $[ followed by statement enter $[

        at com.squareup.javapoet.Util.checkState(Util.java:62)

        at com.squareup.javapoet.CodeWriter.emit(CodeWriter.java:282)

        at com.squareup.javapoet.MethodSpec.emit(MethodSpec.java:139)

        at com.squareup.javapoet.TypeSpec.emit(TypeSpec.java:322)

        at com.squareup.javapoet.JavaFile.emit(JavaFile.java:217)

        at com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:95)

        at com.squareup.javapoet.JavaFile.toString(JavaFile.java:236)

        at com.squareup.javapoet.JavaFile$2.getCharContent(JavaFile.java:251)

        at com.squareup.javapoet.JavaFile$2.getCharContent(JavaFile.java:248)

        at org.javacc.fuzzer.FuzzParserGenerator.generate(FuzzParserGenerator.kt:25)

        at org.javacc.parser.Main.mainProgram(Main.java:259)

        at org.javacc.fuzzer.test.FuzzGenerationTest.generateParser(FuzzGenerationTest.kt:37)

        at org.javacc.fuzzer.test.FuzzGenerationTest.generateParser$default(FuzzGenerationTest.kt:23)

        at org.javacc.fuzzer.test.FuzzGenerationTest.simpleFuzzer$javacc(FuzzGenerationTest.kt:13)



I see there's statement enter $[ followed by statement enter $[, however, the context is not really clear.

Just in case, FuzzParserGenerator.generate(FuzzParserGenerator.kt:25 is

println(file.getCharContent(true)) // file is JavaFileObject produced by JavaPoet

It would be great if JavaPoet could re-construct partially invalid code, and highlight what went wrong (see https://elm-lang.org/news/compiler-errors-for-humans )

It would be nice to have a debug mode, where JavaPoet would record the stacktrace for each Builder generation (or addCode-like call), so it could report the stacktrace (or something like that) where the bad CodeBlock was created.



在我的案例中，我使用 methodBuilder.addStatement()

Method.Builder methodBuilder and CodeBlock code

i fix my bug by replacing methodBuilder.addStatement(code)

with methodBuilder.add(code)
